### ISSUE TITLE
$USER is not set in cron

### ISSUE THREAD

**Issue by kdebisschop** [do-community/ubuntu-1604-mysql-backup#9] opened 2018-04-12 13:51 UTC
Several of these scripts -- including backup-mysql -- use the $USER environment variable to ensure that the user running the script is the assigned backup user. Because $USER is not set by cron, this causes the script to fail unless the default behavior is overridden with an explicit set of USER.

Further, $USER is a convention and not a reliable indicator of the account running the script. I believe `id -un` or `logname` is the preferred way to make this check.

**Comment by imchairmanm** [comment] 2018-04-12 17:23
Hey there.  I'm unable to reproduce your issue here unfortunately (but I agree with you anyways).

Since the cron script is using `sudo -u backup`, all of the environmental variables typically set by `sudo` are applied when running the `backup-mysql.sh` script.  You can find a list of those in the "ENVIRONMENT" section of `man sudo` (`USER` is one of them).  You can validate this by adding a `printenv` to the `/usr/local/bin/backup-mysql.sh` script itself:

```
#!/bin/bash

export LC_ALL=c

# print the current environment
printenv > /tmp/scriptenv
. . .
```

At least on the systems I've tested, `/tmp/scriptenv` has `USER=backup` as expected.

All that being said, I think you're right that it'd be better to use `id --user --name` to get the user since it seems more reliable.  I don't think it matters in this specific instance, but it seems like good practice anyways.  I'm going to close this one and accept your PR.  Thanks for the heads up!

**Closed as completed by imchairmanm** 2018-04-12 17:23 UTC
